# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='my.server.stream.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x15my.server.stream.grpc\" \n\x0b\x43harRequest\x12\x11\n\tcharacter\x18\x01 \x01(\t\"\x1d\n\x0c\x43harResponse\x12\r\n\x05words\x18\x01 \x01(\t2y\n\x1a\x42idirectionalStreamExample\x12[\n\nCharStream\x12\".my.server.stream.grpc.CharRequest\x1a#.my.server.stream.grpc.CharResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_CHARREQUEST = _descriptor.Descriptor(
  name='CharRequest',
  full_name='my.server.stream.grpc.CharRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='character', full_name='my.server.stream.grpc.CharRequest.character', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=72,
)


_CHARRESPONSE = _descriptor.Descriptor(
  name='CharResponse',
  full_name='my.server.stream.grpc.CharResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='my.server.stream.grpc.CharResponse.words', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['CharRequest'] = _CHARREQUEST
DESCRIPTOR.message_types_by_name['CharResponse'] = _CHARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CharRequest = _reflection.GeneratedProtocolMessageType('CharRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHARREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:my.server.stream.grpc.CharRequest)
  })
_sym_db.RegisterMessage(CharRequest)

CharResponse = _reflection.GeneratedProtocolMessageType('CharResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHARRESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:my.server.stream.grpc.CharResponse)
  })
_sym_db.RegisterMessage(CharResponse)



_BIDIRECTIONALSTREAMEXAMPLE = _descriptor.ServiceDescriptor(
  name='BidirectionalStreamExample',
  full_name='my.server.stream.grpc.BidirectionalStreamExample',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='CharStream',
    full_name='my.server.stream.grpc.BidirectionalStreamExample.CharStream',
    index=0,
    containing_service=None,
    input_type=_CHARREQUEST,
    output_type=_CHARRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIDIRECTIONALSTREAMEXAMPLE)

DESCRIPTOR.services_by_name['BidirectionalStreamExample'] = _BIDIRECTIONALSTREAMEXAMPLE

# @@protoc_insertion_point(module_scope)
