# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='my.server.stream.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x15my.server.stream.grpc\"9\n\x0e\x45xampleRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\";\n\x0f\x45xampleResponse\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x15\n\rresponse_data\x18\x02 \x01(\t2\x88\x01\n\x1a\x42idirectionalStreamExample\x12j\n\x13\x42idirectionalStream\x12%.my.server.stream.grpc.ExampleRequest\x1a&.my.server.stream.grpc.ExampleResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_EXAMPLEREQUEST = _descriptor.Descriptor(
  name='ExampleRequest',
  full_name='my.server.stream.grpc.ExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='my.server.stream.grpc.ExampleRequest.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='my.server.stream.grpc.ExampleRequest.request_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=97,
)


_EXAMPLERESPONSE = _descriptor.Descriptor(
  name='ExampleResponse',
  full_name='my.server.stream.grpc.ExampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='my.server.stream.grpc.ExampleResponse.server_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_data', full_name='my.server.stream.grpc.ExampleResponse.response_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['ExampleRequest'] = _EXAMPLEREQUEST
DESCRIPTOR.message_types_by_name['ExampleResponse'] = _EXAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleRequest = _reflection.GeneratedProtocolMessageType('ExampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:my.server.stream.grpc.ExampleRequest)
  })
_sym_db.RegisterMessage(ExampleRequest)

ExampleResponse = _reflection.GeneratedProtocolMessageType('ExampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLERESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:my.server.stream.grpc.ExampleResponse)
  })
_sym_db.RegisterMessage(ExampleResponse)



_BIDIRECTIONALSTREAMEXAMPLE = _descriptor.ServiceDescriptor(
  name='BidirectionalStreamExample',
  full_name='my.server.stream.grpc.BidirectionalStreamExample',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=161,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='BidirectionalStream',
    full_name='my.server.stream.grpc.BidirectionalStreamExample.BidirectionalStream',
    index=0,
    containing_service=None,
    input_type=_EXAMPLEREQUEST,
    output_type=_EXAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIDIRECTIONALSTREAMEXAMPLE)

DESCRIPTOR.services_by_name['BidirectionalStreamExample'] = _BIDIRECTIONALSTREAMEXAMPLE

# @@protoc_insertion_point(module_scope)
