# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='action.proto',
  package='AiiiGRPC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x61\x63tion.proto\x12\x08\x41iiiGRPC\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x04List\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.AiiiGRPC.Item\"4\n\x06\x46ilter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\x12\r\n\x05opStr\x18\x03 \x01(\t2\x86\x02\n\x0bToDoService\x12.\n\x0cUnaryAddItem\x12\x0e.AiiiGRPC.Item\x1a\x0e.AiiiGRPC.List\x12\x42\n\x16\x43lientStreamingAddItem\x12\x0e.AiiiGRPC.Item\x1a\x16.google.protobuf.Empty(\x01\x12<\n\x16ServerStreamingSubList\x12\x10.AiiiGRPC.Filter\x1a\x0e.AiiiGRPC.Item0\x01\x12\x45\n\x1f\x42idirectionalStreamingAsyncList\x12\x0e.AiiiGRPC.Item\x1a\x0e.AiiiGRPC.List(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='AiiiGRPC.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AiiiGRPC.Item.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='AiiiGRPC.Item.price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='AiiiGRPC.Item.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=107,
)


_LIST = _descriptor.Descriptor(
  name='List',
  full_name='AiiiGRPC.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='AiiiGRPC.List.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=146,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='AiiiGRPC.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AiiiGRPC.Filter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='AiiiGRPC.Filter.price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opStr', full_name='AiiiGRPC.Filter.opStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=200,
)

_LIST.fields_by_name['items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'action_pb2'
  # @@protoc_insertion_point(class_scope:AiiiGRPC.Item)
  })
_sym_db.RegisterMessage(Item)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
  'DESCRIPTOR' : _LIST,
  '__module__' : 'action_pb2'
  # @@protoc_insertion_point(class_scope:AiiiGRPC.List)
  })
_sym_db.RegisterMessage(List)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
  'DESCRIPTOR' : _FILTER,
  '__module__' : 'action_pb2'
  # @@protoc_insertion_point(class_scope:AiiiGRPC.Filter)
  })
_sym_db.RegisterMessage(Filter)



_TODOSERVICE = _descriptor.ServiceDescriptor(
  name='ToDoService',
  full_name='AiiiGRPC.ToDoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=203,
  serialized_end=465,
  methods=[
  _descriptor.MethodDescriptor(
    name='UnaryAddItem',
    full_name='AiiiGRPC.ToDoService.UnaryAddItem',
    index=0,
    containing_service=None,
    input_type=_ITEM,
    output_type=_LIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClientStreamingAddItem',
    full_name='AiiiGRPC.ToDoService.ClientStreamingAddItem',
    index=1,
    containing_service=None,
    input_type=_ITEM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServerStreamingSubList',
    full_name='AiiiGRPC.ToDoService.ServerStreamingSubList',
    index=2,
    containing_service=None,
    input_type=_FILTER,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BidirectionalStreamingAsyncList',
    full_name='AiiiGRPC.ToDoService.BidirectionalStreamingAsyncList',
    index=3,
    containing_service=None,
    input_type=_ITEM,
    output_type=_LIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOSERVICE)

DESCRIPTOR.services_by_name['ToDoService'] = _TODOSERVICE

# @@protoc_insertion_point(module_scope)
